language: go

go:
  - "1.13"
  - master

install:
  # Install gometalinter from binary distribution
  - curl -L https://git.io/vp6lP | sh && mv ./bin/* $GOPATH/bin/ && rm -r ./bin
  - export PATH="$GOPATH/bin:$PATH"

script:
  - env GO111MODULE=on make test
  - make lint

after_success:
  - bash <(curl -s https://codecov.io/bash)

deploy:
- provider: script
  skip_cleanup: true
  script: curl -sL https://git.io/goreleaser | bash
  on:
    tags: true
